#端口号
server:
  port: 8085
#指定sql映射文件的位置
mybatis-plus:
  mapper-locations: mapper/*.xml
#系统环境选择配置
spring:
#数据源配置
  datasource:
    #数据源基本配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomi_project?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456